### ISSUE TITLE
[idea] merge needed icons from papirus suite

### ISSUE THREAD

**Issue by FadeMind** [horst3180/arc-icon-theme#1]
@horst3180 papirus icons are under development by @varlesh.
It is available Dark variant too

See:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk

NOTE: icons from -gtk are designed for XFCE/GNOME etc (based on GTK).
-kde flavour is for KDE Plasma 5 (and it is compatible with GTK apps too).

PS.
Varlesh made too:
https://github.com/varlesh/Arc-Dark-KDE 
and recently 
https://github.com/varlesh/VLC-Arc-Dark

good lookin with https://github.com/horst3180/arc-theme.

Regards 

FadeMind

**Comment by alphaphee** [comment]
Papirus icon theme follows the Material Design guidelines, how is it related to Arc Icon theme? @FadeMind

**Comment by FadeMind** [comment]
@alpha for now is not related (and I'm not expert in icon set guide). IMO apps can be taken from papirus and merged (after customs) in to Arc icon theme. It's just my suggestion.
Mokka theme is not maintained (homepage is off). 

Arc icon theme follow what (if not Material Design)? (Noob here :smile: )

**Comment by jgillich** [comment]
Moka seems very well maintained by @snwh, there's been quite a few updates recently, and there's a new web site as well: https://snwh.org/moka

**Comment by FadeMind** [comment]
@jgillich thanks for clarification.

**Comment by snwh** [comment]
@alpha when last I saw it, Papirus did not seem to follow Material Design guidelines.

Currently it appears to be a tweaked version of my Paper theme.

**Comment by varlesh** [comment]
Papirus is not Material Design, it's mix Flat and Material...

**Comment by varlesh** [comment]
And Papirus not reconstruct idea Arc icon theme and style, it's my improvisation )). I know need clear-cut icons with shadow, very simple and orderly... Sorry guys

**Comment by varlesh** [comment]
@snwh  @horst3180  It's not my idea. @FadeMind please close issue, because it's different style... I make Arc Dark Theme only KDE, but Arc themes created only GTK. It's only improvisation... for KDE!

**Comment by alphaphee** [comment]
I know @FadeMind was just trying to help, no worries @varlesh.
