### ISSUE TITLE
Question - Missing icons

### ISSUE THREAD

**Issue by kossa** [horst3180/arc-icon-theme#29]
Hi,

I installed arc-flatabulous-theme and arc-icon-theme, I see a lot of icon are missing, and I did not found them in repo, or may be I did not installed theme well :)

![image](https://cloud.githubusercontent.com/assets/1175584/19408130/d03af0b8-92ad-11e6-8b5b-dc9fbc606e92.png)

**Comment by NicoHood** [comment]
How about reading the readme?

**Comment by kossa** [comment]
Alright thanks :)
