### ISSUE TITLE
Fix Calendar on Pantheon

### ISSUE THREAD

**Issue by btd1337** [horst3180/arc-icon-theme#39]
Fix calendar blank numbers for dark variant on pantheon shell.

![captura de tela de 2017-02-05 20 01 14](https://cloud.githubusercontent.com/assets/11943860/22630268/108f0ee0-ebde-11e6-83bc-d5b43cfa76f4.jpeg)

**Comment by knight-corvi** [comment]
This is an issue with the GTK theme rather than the icon theme as far as I can tell.

**Comment by btd1337** [comment]
Uou fail!!

I'm wrong repository. Sorry!
