### ISSUE TITLE
alarm, bluetooth, sound and power icons huge and battery small

### ISSUE THREAD

**Issue by dugagjin** [horst3180/arc-icon-theme#40]
Hi, 

First, thanks for this beautiful theme! 
I started using ElementaryOS which I applied the arc-theme + arc icons. But not everything went as expected. My panel looks like this:
![howitis](https://cloud.githubusercontent.com/assets/16219574/23822645/372b83ca-0651-11e7-810a-859082cfacce.png)
My inherits are:
```
Inherits=Paper,Adwaita,gnome,hicolor
```
While it should be something like this:
![howitshould](https://cloud.githubusercontent.com/assets/16219574/23822644/372b4216-0651-11e7-8df6-1bac7fa1e928.png)

I tried to fix it but I didn't succeed.  How can I solve this?

**Comment by dugagjin** [comment]
Closed due inactivity

**Comment by NicoHood** [comment]
Please reopen the issue here. We have a new fork to continue maintaining this great icon theme:
https://github.com/nicohood/arc-icon-theme
